project:
  type: website
  output-dir: docs
  
  
website:
  title: "Data Analytics Bootcamp"
  favicon: img/favicon.png
  site-url: https://hovhannisyan91.github.io/aca
  sidebar:
    style: floating
    collapse-level: 1
    search: true
    contents:
      # - text: Home
      #   href: index.qmd
      - text: Syllabus
        href: materials/syllabus.qmd

      - section: Statistical Thinking
        href: materials/statistics/index.qmd
        contents:
          - auto: materials/statistics
            sort: asc
            pattern: "session*.qmd"
            exclude: ["**/index.qmd"]
      - section: SQL
        href: materials/sql/index.qmd
        contents:
          - auto: materials/sql
            sort: asc
            pattern: "session*.qmd"
            exclude: ["**/index.qmd"]
      - section: Python
        href: materials/python/index.qmd
        contents:
          - auto: materials/python
            sort: asc
            pattern: "session*.qmd"
            exclude: ["**/index.qmd"]
      - section: Tableau
        href: materials/tableau/index.qmd
        contents:
          - auto: materials/tableau
            sort: asc
            pattern: "session*.qmd"
            exclude: ["**/index.qmd"]
  navbar:
    logo: img/favicon.png
    back-to-top-navigation: true
    left:
      # - text: "Home"
      #   href: index.qmd
      - text: "Syllabus"
        href: materials/syllabus.qmd
      - text: "Statistical Thinking"
        href: materials/statistics/index.qmd
      - text: "SQL"
        href: materials/sql/index.qmd
      - text: "Python"
        href: materials/python/index.qmd
      - text: "Tableau"
        href: materials/tableau/index.qmd
      - text: "Lab"
        href: materials/lab/index.qmd
  
    right:
      - icon: github
        href: https://github.com/hovhannisyan91
        aria-label: GitHub
  

format: 
  html:
    page-layout: full
    theme: 
      light: cosmo
      dark: cyborg
    toc: true
    toc-depth: 3
    toc-location: right
    code-fold: false
    css: styles.css
