name: Sync SQL Module to Portfolio Root

on:
  push:
    branches: [ main ]
    paths:
      - "lab/sql_module/**"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Checkout sql-analytics-portfolio
        uses: actions/checkout@v4
        with:
          repository: hovhannisyan91/sql-analytics-portfolio
          token: ${{ secrets.SQL_PORTFOLIO_PAT }}
          path: portfolio

      - name: Sync sql_module into repo root
        run: |
          rsync -av --delete \
            lab/sql_module/ \
            portfolio/

      - name: Commit and push if changed
        run: |
          cd portfolio
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Sync SQL module to portfolio root"
          git push
